# Лаборатоная работа №1
## Выполнила студентка группы БСТ2004 Шадюк Мария

### Задание №1
1. Создать Jupyter Notebook со следующим наименованием: Lab1_Группа_ФИО
2. Создать новую ячейку с помощью кнопки +
3. В созданной ячейке по указанной ниже форме заполните оглавление файла,
заменив наименование группы и вписав свое ФИО, после чего создайте еще одну ячейку и напишите следующий код, выводящий надпись "Hello World"
4. С помощью кнопки "Run" запустите выполнение всех ячеек.
5. После выполнения у вас должна отформатироваться ячейка с оглавлением и должен выполниться “Hello, World!” 

In [12]:
print('Hello World')

Hello World


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер матрицы, а min_lim и max_lim - минимальное и максимальное значение для генерируемого числа . По умолчанию при отсутствии параметров принимать следующие значения:
m = 50
n = 50
min_limit = -250
max_limit = 1000 + (номер своего варианта)

In [13]:
import numpy as np
import timeit
import math


In [14]:
m=50
n=50
min_limit=-250
max_limit=1022

m2=input("\n\nВведите m: ")
if len(m2)>0: m=int(m2)

n2=input("Введите n: ")
if len(n2)>0: n=int(n2)

min_limit2=input("Введите минимальное значение: ")
if len(min_limit2)>0: min_limit=int(min_limit2)

max_limit2=input("Введите максимальное значение: ")
if len(max_limit2)>0: max_limit=int(max_limit2)

arr=np.random.randint(min_limit, max_limit,size=(m, n))
print(arr)

[[ 7 -8  5 -2 -2]
 [-2  8 -2  1 -7]
 [-1  0  5  8 -9]
 [ 6  2 -1  1 -4]
 [ 1 -3  7  3  6]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.
Методы: Выбором, Вставкой, Обменом, Шелла, Турнирная, Быстрая, Пирамидальная

#### Сортировка выбором

In [15]:
# Сортировка выбором
def selection_sort(arr):
    for row in range(len(arr)):
        for i in range(0, len(arr[row]) - 1): 
            min_idx = i 
            for j in range(i+1, len(arr[row])): 
                if arr[row][min_idx] > arr[row][j]: 
                    min_idx = j 
            arr[row][i], arr[row][min_idx] = arr[row][min_idx], arr[row][i]

selection_sort(arr)
print(arr)


[[-8 -2 -2  5  7]
 [-7 -2 -2  1  8]
 [-9 -1  0  5  8]
 [-4 -1  1  2  6]
 [-3  1  3  6  7]]


#### Сортировка вставкой

In [16]:
# Сортировка вставкой
def insertion_sort(arr):
    for row in range(len(arr)):
        for i in range(1, len(arr[row])):
            #кладем сюда значение ячейки, что бы потом вставить его в нужное место
            temp = arr[row][i]              
            j = i - 1
            #этим циклом проверяем значение каждой ячейки слева от i,
            # до тех пор пока не наткнемся на значение меньше данного 
            while (j>=0 and temp < arr[row][j]):
                #здесь сдвигаем все направо пока не найдем меньше данного
                arr[row][j + 1] = arr[row][j]
                j -= 1
            # сама вставка
            arr[row][j+1]=temp

insertion_sort(arr)
print(arr)

[[-8 -2 -2  5  7]
 [-7 -2 -2  1  8]
 [-9 -1  0  5  8]
 [-4 -1  1  2  6]
 [-3  1  3  6  7]]


#### Сортировка обменом

In [17]:
def bubble_sort(arr):
    for row in range(len(arr)):
        for j in range(len(arr[row])-1):
            if arr[row][j + 1] < arr[row][j]:
               arr[row][j],  arr[row][j + 1] =  arr[row][j + 1],  arr[row][j]
                    
bubble_sort(arr)
print (arr)



[[-8 -2 -2  5  7]
 [-7 -2 -2  1  8]
 [-9 -1  0  5  8]
 [-4 -1  1  2  6]
 [-3  1  3  6  7]]


#### Сортировка Шелла

In [18]:
def shellSort(array):
    for row in range(len(array)):
        n = len(array[row])         
        k = int(math.log2(n))
        interval = 2**k -1
        # пока наш шаг больше 0 продолжаем цикл
        while interval > 0:
            for i in range(interval, n):
                temp = array[row][i]
                j = i
                #сравниваем два массива находящихся на рассоянии в interval
                while j >= interval and array[row][j - interval] > temp:
                    #если значение в левой части больше значения в правой, то
                    # меняем их местами
                    array[row][j] = array[row][j - interval]
                    j -= interval
                array[row][j] = temp
            k -= 1
            interval = 2**k -1
    return array

shellSort(arr)
print(arr)

[[-8 -2 -2  5  7]
 [-7 -2 -2  1  8]
 [-9 -1  0  5  8]
 [-4 -1  1  2  6]
 [-3  1  3  6  7]]


#### Быстрая сортировка

In [19]:
def QuickSort(arr):
    for i in range(len(arr)):
        quickSort(0,len(arr[i])-1,arr,i)
    return arr
#обозначаем перыый последний и середину массива
def quickSort(_first, _last, array, row):
    first=int(_first)
    last=int(_last)
    middle=int((first+last)/2)
    
    while (first<last):
        #пока число слева от миддл меньше, то переходим к следующему
        while( array[row][first] < array[row][middle]): 
            first+=1
        #пока крайнее число больше середины переходим к следующему
        while( array[row][last] > array[row][middle]):
            last-=1
       #меняем местами массивы если первый меньше ласт
        if(first<=last):
            array[row][first],array[row][last]=array[row][last],array[row][first]
            first+=1
            last-=1
    
    if(_first<last):
        quickSort(_first,last,array,row)
    if(first<_last):
        quickSort(first,_last,array,row)

QuickSort(arr)
print(arr)

[[-8 -2 -2  5  7]
 [-7 -2 -2  1  8]
 [-9 -1  0  5  8]
 [-4 -1  1  2  6]
 [-3  1  3  6  7]]


#### Пирамидальная сортировка

In [20]:
#Пирамидальная сортировка
def heapify(arr, n, i):
    #соседи слева и справа
    largest = i
    l = 2 * i + 1 
    r = 2 * i + 2

    #меняем корневого на левого если левый больше
    if l < n and arr[i] < arr[l]:
        largest = l

    #меняем корневого на правого если пр больше
    if r < n and arr[largest] < arr[r]:
        largest = r

    if largest != i:
        arr[i],arr[largest] = arr[largest],arr[i]

        heapify(arr, n, largest)


def HeapSort(arr):
    for i in range(len(arr)):
        #число по лен
        n = len(arr[i])
        #шагаем по массиву сортировкой числом от Н до -1, с шагом -1
        for j in range(n, -1, -1):
            heapify(arr[i], n, j)
        #сама сортировка
        for j in range(n-1, 0, -1):
            arr[i][j], arr[i][0] = arr[i][0], arr[i][j] 
            heapify(arr[i], j, 0)
    return arr
HeapSort(arr)
print(arr)



[[-8 -2 -2  5  7]
 [-7 -2 -2  1  8]
 [-9 -1  0  5  8]
 [-4 -1  1  2  6]
 [-3  1  3  6  7]]


In [21]:
print("Сортировка выбором выполнилась за ")
arr=np.random.randint(min_limit, max_limit,size=(m, n))
start_time = timeit.default_timer()
selection_sort(arr)
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Сортировка вставкой выполнилась за ")
arr=np.random.randint(min_limit, max_limit,size=(m, n))
start_time = timeit.default_timer()
insertion_sort(arr)
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Сортировка обменом выполнилась за ")
arr=np.random.randint(min_limit, max_limit,size=(m, n))
start_time = timeit.default_timer()
bubble_sort(arr)
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Сортировка Шелла выполнилась за ")
arr=np.random.randint(min_limit, max_limit,size=(m, n))
start_time = timeit.default_timer()
shellSort(arr)
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Сортировка Быстрая выполнилась за ")
arr=np.random.randint(min_limit, max_limit,size=(m, n))
start_time = timeit.default_timer()
QuickSort(arr)
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Сортировка Пирамидальная выполнилась за ")
arr=np.random.randint(min_limit, max_limit,size=(m, n))
start_time = timeit.default_timer()
HeapSort(arr)
time_2 = timeit.default_timer() - start_time
print(time_2)

print("Сортировка Встроенная выполнилась за ")
arr=np.random.randint(min_limit, max_limit,size=(m, n))
start_time = timeit.default_timer()
sorted(arr)
time_2 = timeit.default_timer() - start_time
print(time_2)

Сортировка выбором выполнилась за 
0.00022230000467970967
Сортировка вставкой выполнилась за 
0.00017010000010486692
Сортировка обменом выполнилась за 
0.00015230001008603722
Сортировка Шелла выполнилась за 
0.00019130000146105886
Сортировка Быстрая выполнилась за 
0.0002614000113680959
Сортировка Пирамидальная выполнилась за 
0.00021749999723397195
Сортировка Встроенная выполнилась за 


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()